### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by nmilosev**
Hello Jack!

Thank you for your awesome library. It really is awesome, and so are you! :)

I'm a Linux user, so I worked a bit last night to make it all click on Mono on Fedora 25.

As you can see, you've done a good job, and only a couple of small modifications are needed for this thing to fly on Linux.

Thank you again! :)

Changes:
- Small modification to path in GPUProvider, so it works on both path separators
- README update for Linux support

TODO: 
- Detect when running on Linux, and do automatic library redirection, so that the user doesn't have to copy ManagedCuda config files.

### CODE REVIEW

**Comment by jdermody** [comment]
Thanks for the kind words! I'm glad you liked it.

And good job getting it going on Linux!

**Comment by nmilosev** [comment]
Thanks for the merge!

Here is a screenshot of it running on Linux, sorry for forgetting to include it. :)

screenshot from 2017-02-14 15-11-25

The more I play with this library the more I love it! It's really well engineered :)

If you need help in implementing some new bits, I would love to get involved, just let me know. I started my PhD in October, with focus on ANN's and would love to work with you on this library. :)

Thank you again for creating it.

Hope you are well,

Nemanja

**Comment by jdermody** [comment]
Hi Nemanja

Sounds great - of course you're welcome to contribute!

Personally, I'm fascinated by neural networks and they're something I want to expand on in Bright Wire.

I would love to add some differentiable neural computer architectures (Neural Turing Machines, Memory Networks, Neural Stacks, Hierarchical Attentive Memory etc) moving forward.

What areas are you interested in?

Cheers,
Jack

**Comment by nmilosev** [comment]
That's great, thank you!

I've just started learning about ANN's so sorry for not knowing a lot (I come from a more developery side of things :) ). I've read about Neural Turing Machines and I am very interested in them. Maybe we can do something with that! :)

I will let you know as soon as I get to my research a bit further, still have a lot to learn.

Cheers,
Nemanja

**Comment by jdermody** [comment]
Sounds good! I have a development background as well (and a belief that machine learning IS the future of software development ; )

I've added some items to the [project roadmap](https://github.com/jdermody/brightwire/projects/1) - there are some smaller pieces apart from working on The Singularity if you're keen.

Best,
Jack

**Pull request merged**
